/**
 * Reads pre-fetched stock data from public/data/stocks.json.
 *
 * This file is generated by `npm run fetch-stocks` (scripts/fetchStocks.ts)
 * and committed to the repo weekly via GitHub Actions. Vercel auto-deploys
 * when the file changes, making the dashboard truly update on a schedule
 * without any API calls at runtime.
 *
 * Server-side only — uses Node.js fs module.
 */

import { readFileSync } from "fs";
import path from "path";
import { StockData } from "./stockData";

interface StocksFile {
  stocks: StockData[];
  lastUpdated: string;
  fetchedCount: number;
  durationMs: number;
}

let _cache: StocksFile | null = null;

export function loadAllStocks(): StocksFile {
  // In dev, re-read every time. In production, cache in module memory.
  if (_cache && process.env.NODE_ENV === "production") return _cache;

  try {
    const filePath = path.join(process.cwd(), "public", "data", "stocks.json");
    const raw = readFileSync(filePath, "utf-8");
    _cache = JSON.parse(raw) as StocksFile;
    return _cache;
  } catch {
    // File doesn't exist yet (before first GitHub Actions run)
    return {
      stocks: [],
      lastUpdated: new Date().toISOString(),
      fetchedCount: 0,
      durationMs: 0,
    };
  }
}

export function loadStock(ticker: string): StockData | null {
  const { stocks } = loadAllStocks();
  return stocks.find((s) => s.ticker === ticker.toUpperCase()) ?? null;
}
