/**
 * Reads pre-fetched stock data from public/data/stocks.json.
 *
 * This file is generated by `npm run fetch-stocks` (scripts/fetchStocks.ts)
 * and committed to the repo weekly via GitHub Actions. Vercel auto-deploys
 * when the file changes, making the dashboard truly update on a schedule
 * without any API calls at runtime.
 *
 * Server-side only — uses Node.js fs module.
 */

import { readFileSync } from "fs";
import path from "path";
import { StockData } from "./stockTypes";

interface StocksFile {
  stocks: StockData[];
  lastUpdated: string;
  fetchedCount: number;
  durationMs: number;
}

let _cache: StocksFile | null = null;

export function loadAllStocks(): StocksFile {
  // In dev, re-read every time. In production, cache in module memory.
  if (_cache && process.env.NODE_ENV === "production") return _cache;

  try {
    const filePath = path.join(process.cwd(), "public", "data", "stocks.json");
    const raw = readFileSync(filePath, "utf-8");
    const parsed = JSON.parse(raw) as StocksFile;
    // Sanitise any Date-string values that yahoo-finance2 may have serialised
    // into numeric fields (e.g. sharesShortPriorMonth stored as ISO string).
    const ISO_DATE_RE = /^\d{4}-\d{2}-\d{2}T/;
    parsed.stocks = parsed.stocks.map((s) => ({
      ...s,
      sharesShort: typeof s.sharesShort === "string" && ISO_DATE_RE.test(s.sharesShort as unknown as string) ? null : s.sharesShort,
      sharesShortPriorMonth:
        typeof s.sharesShortPriorMonth === "string" &&
        ISO_DATE_RE.test(s.sharesShortPriorMonth as unknown as string)
          ? null
          : s.sharesShortPriorMonth,
      floatShares: typeof s.floatShares === "string" && ISO_DATE_RE.test(s.floatShares as unknown as string) ? null : s.floatShares,
    }));
    _cache = parsed;
    return _cache;
  } catch {
    // File doesn't exist yet (before first GitHub Actions run)
    return {
      stocks: [],
      lastUpdated: new Date().toISOString(),
      fetchedCount: 0,
      durationMs: 0,
    };
  }
}

export function loadStock(ticker: string): StockData | null {
  const { stocks } = loadAllStocks();
  return stocks.find((s) => s.ticker === ticker.toUpperCase()) ?? null;
}
